CRM/CRM/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    # crm相关业务
    url(r'^crm/', include('sales.urls')),

]

CRM/sales/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe


# Create your models here.


class UserInfo(models.Model):
    """
    用户表
    """
    username = models.CharField(max_length=16)
    password = models.CharField(max_length=32)
    email = models.EmailField()
    telephone = models.CharField(max_length=16)
    is_active = models.BooleanField(default=True)

    def __str__(self):

        return self.username


source_type = (
    ('qq', 'qq群'),
    ('referral', '内部转介绍'),
    ('website', '官方网站'),
    ('baidu_ads', '百度推广'),
    ('office_direct', '直接上门'),
    ('WoM', '口碑'),
    ('public_class', '公开课'),
    ('website_luffy', '路飞官网'),
    ('others', '其它'),
)

course_choices = (
    ('LinuxL', 'Linux中高级'),
    ('PythonFullStack', 'Python高级全栈开发')
)

class_type_choices = (
    ('fulltime', '脱产班'),
    ('online', '网络班'),
    ('weekend', '周末班'),
)

enroll_status_choices = (
    ('signed', '已报名'),
    ('unregistered', '未报名'),
    ('studying', '学习中'),
    ('paid_in_full', '学费已交齐'),
)

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField("QQ", max_length=64, unique=True, help_text="QQ号必须唯一")
    qq_name = models.CharField("QQ昵称", max_length=64, blank=True, null=True)
    name = models.CharField("姓名", max_length=32, blank=True, null=True, help_text="学生报名后，名字改为真实姓名")
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField("手机号", blank=True, null=True)
    source = models.CharField("客户来源", max_length=64, choices=source_type, default="qq")
    introduce_from = models.ForeignKey("self", verbose_name="转介绍自学员", blank=True, null=True, on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices)  # 多选，并且存成一个列表,通过ModelForm来用的时候，会成为多选框
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True)
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default='unregistered',
                              help_text='选择客户此时的状态')
    date = models.DateTimeField("咨询日期", auto_now_add=True)  # 这个没啥用昂，销售说是为了一周年的时候给客户发一个祝福信息啥的
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)  # 考核销售的跟进情况，如果多天没有跟进，会影响销售的绩效等
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)  # 销售自己大概记录一下自己下一次会什么时候跟进，也没啥用
    # 用户表中存放的是自己公司的所有员工。
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", related_name='customers', blank=True, null=True,
                                   on_delete=models.CASCADE)
    # 一个客户可以报多个班，报个脱产班，再报个周末班等，所以是多对多。
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True)

    # 配置给127.0.0.1/admin使用
    class Meta:
        ordering = ['id', ]
        verbose_name = '客户信息表'
        verbose_name_plural = '客户信息表'

    def __str__(self):
        return self.name + ":" + self.qq

    def status_show(self):
        status_color = {
            'unregistered': 'red',
            'signed': 'orange',
            'studying': 'yellow',
            'paid_in_full': 'green'
        }

        return mark_safe("<span style='background-color: {0}'>{1}</span>".format(status_color[self.status], self.get_status_display()))


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")  # python20期等
    campuses = models.ForeignKey('Campuses', verbose_name="校区", on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)  # 不一定什么时候结业，哈哈，所以可为空

    teachers = models.ManyToManyField('UserInfo', verbose_name="老师")  # 对了，还有一点，如果你用的django2版本的，那么外键字段都需要自行写上on_delete=models.CASCADE

    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班级及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", "campuses")

    def __str__(self):
        return '{}{}({})'.format(self.get_course_display(), self.semester, self.campuses)


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name='所咨询客户')
    note = models.TextField(verbose_name='跟进内容')
    status = models.CharField('跟进状态', max_length=8, choices=seek_status_choices, help_text='选择客户此时的状态')
    consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """
    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    # contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')

    def __str__(self):
        return self.customer.name

CRM/sales/views/customer.py
# __author = wulinjun
# date:2020/6/10 1:04
from django.conf import settings
from django.db.models import Q
from django.db import transaction
from django.shortcuts import render, redirect, HttpResponse
from django.urls import reverse
from django.views import View

from sales import models
from sales.myforms import (CustomerForm, ConsultRecordForm, EnrollForm)
from sales.utils.paging import PageInfo


# Create your views here.

# 首页
def home(request):
    return render(request, 'saleshtml/home.html')


# 公私户相关信息验证
class CustomerView(View):

    def get(self, request):

        current_request_path = request.path
        # 公户
        if current_request_path == reverse('customers'):
            tag = '1'
            customer_list = models.Customer.objects.filter(consultant__isnull=True)
        # 私户请求
        else:
            tag = '2'
            user_obj = request.user_obj
            customer_list = models.Customer.objects.filter(consultant=user_obj)

        get_data = request.GET.copy()  # 获取get请求提交的数据

        # 当前页
        current_page = request.GET.get('page')  # 当前页码
        kw = request.GET.get('kw')  # 查询关键字
        search_field = request.GET.get('search_field')
        if kw:
            kw = kw.strip()
            q_obj = Q()
            q_obj.children.append((search_field, kw))
            customer_list = customer_list.filter(q_obj)
        else:
            customer_list = customer_list

        try:
            current_page = int(current_page)

        except Exception as e:
            current_page = 1

        # 每页显示的个数
        per_page = 10

        start_show = (current_page - 1) * per_page
        end_show = current_page * per_page
        # 每页显示的数据
        customers_obj = customer_list.reverse()[start_show: end_show]
        all_count = customer_list.count()
        page_info = PageInfo(current_page=current_page, all_count=all_count, per_page=per_page, get_data=get_data,
                             base_url=request.path,
                             show_page=5)
        return render(request, 'saleshtml/customers.html',
                      {'customers_obj': customers_obj, 'page_info': page_info, 'tag': tag})

    def post(self, request):

        action = request.POST.get('action')
        cids = request.POST.getlist('cids')
        if hasattr(self, action):

            ret = getattr(self, action)(request, cids)
            if ret:
                return ret
            return redirect(request.path)

    # 公转私
    def reverse_gs(self, request, cids):

        with transaction.atomic():
            customers = models.Customer.objects.filter(pk__in=cids, consultant__isnull=True)
        if customers.count() != len(cids):
            return HttpResponse('公转私失败，请刷新页面重新尝试！！')
        customers.update(consultant_id=request.session.get('user_id'))

    # 私转公
    def reverse_sg(self, request, cids):
        customers = models.Customer.objects.filter(pk__in=cids, consultant__isnull=False)
        if customers.count() != len(cids):
            return HttpResponse('私转公失败，请刷新页面重新尝试！！')
        customers.update(consultant=None)


# 添加和编辑客户信息
def add_edit_customers(request, cid=None):
    """
    添加和编辑客户
    :param request:
    :return:
    """
    label = "编辑页面" if cid else "添加页面"
    customer_obj = models.Customer.objects.filter(pk=cid).first()
    if request.method == 'GET':
        customer_form = CustomerForm(instance=customer_obj)
        return render(request, 'saleshtml/edit_customers.html', {'customer_form': customer_form, 'label': label})

    else:
        next_url = request.GET.get('next')
        customer_form = CustomerForm(request.POST, instance=customer_obj)
        if customer_form.is_valid():
            customer_form.save()
            if next_url:
                return redirect(next_url)
            else:
                return redirect('customers')
        else:
            return render(request, 'saleshtml/edit_customers.html', {'customer_form': customer_form, 'label': label})


# 跟进记录
class ConsultRecord(View):

    def get(self, request):

        cid = request.GET.get('cid')

        if cid:
            # 当前登录用户的未删除的客户的跟进记录
            consult_list = models.ConsultRecord.objects.filter(consultant=request.user_obj, delete_status=False,
                                                               customer_id=cid).order_by('-date')
        else:
            consult_list = models.ConsultRecord.objects.filter(consultant=request.user_obj,
                                                               delete_status=False).order_by('-date')

        # 分页和搜索
        get_data = request.GET.copy()  # 获取get请求提交的数据

        # 当前页
        current_page = request.GET.get('page')  # 当前页码
        kw = request.GET.get('kw')  # 查询关键字
        search_field = request.GET.get('search_field')
        if kw:
            kw = kw.strip()
            q_obj = Q()
            q_obj.children.append((search_field, kw))
            consult_list = consult_list.filter(q_obj)
        else:
            consult_list = consult_list

        try:
            current_page = int(current_page)

        except Exception as e:
            current_page = 1

        # 每页显示的个数
        per_page = 10

        start_show = (current_page - 1) * per_page
        end_show = current_page * per_page
        # 每页显示的数据
        consult_obj = consult_list.reverse()[start_show: end_show]
        all_count = consult_list.count()
        page_info = PageInfo(current_page=current_page, all_count=all_count, per_page=per_page, get_data=get_data,
                             base_url=request.path,
                             show_page=5)
        return render(request, 'saleshtml/consultrecord.html',
                      {'consult_list': consult_obj, 'page_info': page_info})

    def post(self, request):
        action = request.POST.get('action')
        cids = request.POST.getlist('cids')
        if hasattr(self, action):
            consults = models.ConsultRecord.objects.filter(pk__in=cids)
            # print(customers)
            getattr(self, action)(request, consults)
            return redirect(request.path)

    # 公转私
    def bulk_delete(self, request, consults):
        consults.update(delete_status=True)


# 新增和编辑客户记录
class AddEditConsultView(View):

    def get(self, request, cid=None):

        """
            添加客户和编辑客户
            :param request:
            :param cid:   客户记录id
            :return:
            """
        label = '编辑跟进记录' if cid else '添加跟进记录'
        consult_obj = models.ConsultRecord.objects.filter(pk=cid).first()

        if request.method == 'GET':
            consult_form = ConsultRecordForm(request, instance=consult_obj)
            return render(request, 'saleshtml/add_edit_consult.html', {'consult_form': consult_form, 'label': label})

    def post(self, request, cid=None):
        consult_obj = models.ConsultRecord.objects.filter(pk=cid).first()
        next_url = request.GET.get('next')
        if not next_url:
            next_url = reverse('consult_record')
        consult_form = ConsultRecordForm(request, request.POST, instance=consult_obj)
        if consult_form.is_valid():
            consult_form.save()

            return redirect(next_url)
        else:
            return render(request, 'saleshtml/add_edit_consult.html', {'consult_form': consult_form})


# 删除单条跟进记录
def delete_consult_record(request, cid):
    models.ConsultRecord.objects.filter(pk=cid).update(delete_status=True)
    return redirect('consult_record')


# 报名记录展示
class EnrollmentView(View):

    def get(self, request):

        cid = request.GET.get('cid')
        if cid:
            # 当前登录用户的未删除的客户的跟进记录
            enroll_list = models.Enrollment.objects.filter(customer__consultant=request.user_obj, delete_status=False,
                                                               customer_id=cid).order_by('-enrolled_date')
        else:
            enroll_list = models.Enrollment.objects.filter(customer__consultant=request.user_obj,
                                                               delete_status=False).order_by('-enrolled_date')
        # 分页和搜索
        get_data = request.GET.copy()  # 获取get请求提交的数据

        # 当前页
        current_page = request.GET.get('page')  # 当前页码
        kw = request.GET.get('kw')  # 查询关键字
        search_field = request.GET.get('search_field')
        if kw:
            kw = kw.strip()
            q_obj = Q()
            q_obj.children.append((search_field, kw))
            enroll_list = enroll_list.filter(q_obj)
        else:
            enroll_list = enroll_list

        try:
            current_page = int(current_page)

        except Exception as e:
            current_page = 1

        # 每页显示的个数
        per_page = 10

        start_show = (current_page - 1) * per_page
        end_show = current_page * per_page
        # 每页显示的数据
        enroll_obj = enroll_list.reverse()[start_show: end_show]
        all_count = enroll_list.count()
        page_info = PageInfo(current_page=current_page, all_count=all_count, per_page=per_page, get_data=get_data,
                             base_url=request.path,
                             show_page=5)
        return render(request, 'saleshtml/enrollments.html',
                      {'enrolls': enroll_obj, 'page_info': page_info})

    def post(self, request):
        action = request.POST.get('action')
        cids = request.POST.getlist('cids')
        if hasattr(self, action):
            enrolls = models.Enrollment.objects.filter(pk__in=cids)
            getattr(self, action)(request, enrolls)
            return redirect(request.path)

    # 批量删除报名记录
    def bulk_enroll_record(self, request, enrolls):
        # enrolls.update(delete_status=True)
        enrolls.delete()


# 新增和编辑报名记录
class AddEditEnrollView(View):

    def get(self, request, cid=None):

        """
            添加报名记录和编辑报名记录
            :param request:
            :param cid:   客户记录id
            :return:
            """
        label = '编辑报名记录' if cid else '添加报名记录'

CRM/templates/saleshtml/add_customers.html
{% extends 'starter.html' %}

{% block content %}


    <form class="form-horizontal" novalidate method="post">
    {% csrf_token %}
        {% for field in customer_form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-6">
                    {{ field }}
                </div>

                <div class="col-sm-4">
                    {{ field.errors.0 }}
                </div>
            </div>
        {% endfor %}

        <button class="btn btn-success">提交</button>
    </form>



{% endblock %}

CRM/templates/saleshtml/add_edit_consult.html
{% extends 'starter.html' %}


{% block pageheader %}
    <h1>
{#        {{ label }}#}
    </h1>
{% endblock %}


{% block content %}


    <form class="form-horizontal" novalidate method="post" action="">
        {% csrf_token %}
        {% for field in consult_form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-6">
                    {{ field }}
                </div>

                <div class="col-sm-4">
                    {{ field.errors.0 }}
                </div>
            </div>
        {% endfor %}

        <button class="btn btn-success">提交</button>
    </form>

{% endblock %}

CRM/templates/saleshtml/add_edit_enroll.html
{% extends 'starter.html' %}


{% block pageheader %}
    <h1>
{#        {{ label }}#}
    </h1>
{% endblock %}


{% block content %}


    <form class="form-horizontal" novalidate method="post" action="">
        {% csrf_token %}
        {% for field in enroll_form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-6">
                    {{ field }}
                </div>

                <div class="col-sm-4">
                    {{ field.errors.0 }}
                </div>
            </div>
        {% endfor %}

        <button class="btn btn-success">提交</button>
    </form>

{% endblock %}

CRM/templates/saleshtml/consultrecord.html
{% extends 'starter.html' %}

{% block pageheader %}
    <h1>

    跟进记录展示
    </h1>
{% load mytags %}
{% endblock %}

{% block content %}
    <a href="{% url 'add_consult_record' %}" class="btn btn-primary">
        添加跟进记录
    </a>

    <div class="form-inline">
        <form action="" class="pull-right">
            <div class="form-group pull-right">
                <select name="search_field" id="search_field" class="form-control">
                    <option value="customer__name__contains">客户名称</option>
                </select><input type="text" class="form-control" name="kw" id="key_word" placeholder="请输入关键字"
                                autocomplete="off">
                <button type="submit" class="btn btn-primary">搜索</button>
            </div>
        </form>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group pull-left">
                <select name="action" id="action" class="form-control">

                    <option value="bulk_delete">批量删除</option>


                </select>
                <button class="btn btn-warning">go</button>
            </div>

            <table class="table table-hover table-striped table-bordered">
                <thead>
                <tr>
                    <th><input type="checkbox" id="select_all"> 选择</th>
                    <th>序号</th>
                    <th>所咨询客户</th>
                    <th>跟进内容</th>
                    <th>跟进状态</th>
                    <th>跟进人</th>
                    <th>跟进日期</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for consult in consult_list %}
                    <tr>
                        <td><input type="checkbox" name="cids" value="{{ consult.pk }}"></td>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ consult.customer.name }}</td>
                        <td>{{ consult.note }}</td>
                        <td>{{ consult.get_status_display }}</td>
                        <td>{{ consult.consultant }}</td>
                        <td>{{ consult.date|date:'Y-m-d H:i:s' }}</td>
                        <td>
{#                            <a href="{% resole_url request 'edit_customers' foo.pk %}" class="fa fa-edit">编辑</a>#}
                            <a href="{% resole_url request 'edit_consult_record' consult.pk %}" class="fa fa-edit">编辑</a>
                            <a href="{% url 'delete_consult_record' consult.pk %}" class="fa fa-remove">删除</a>
                        </td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>

            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {{ page_info.pager | safe }}
                </ul>
            </nav>
        </form>


    </div>

{% endblock content %}

CRM/templates/saleshtml/customers.html
{% extends 'starter.html' %}

{% block pageheader %}
    <h1>
{#        {% if tag == '1' %}#}
{#            公户信息#}
{#        {% else %}#}
{#            我的客户信息#}
{#        {% endif %}#}

    {% load mytags %}
    {% reverse_url request %}
    </h1>

{% endblock %}

{% block content %}
    <a href="{% url 'add_customers' %}" class="btn btn-primary">
        添加客户
    </a>

    <div class="form-inline">
        <form action="" class="pull-right">
            <div class="form-group pull-right">
                <select name="search_field" id="search_field" class="form-control">
                    <option value="qq__contains">qq</option>
                    <option value="name__contains">姓名</option>
{#                    <option value="status__contains">状态</option>#}
                </select><input type="text" class="form-control" name="kw" id="key_word" placeholder="请输入关键字"
                                autocomplete="off">
                <button type="submit" class="btn btn-primary">搜索</button>
            </div>
        </form>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group pull-left">
                <select name="action" id="action" class="form-control">
                    {% if tag == '1' %}
                        <option value="reverse_gs">公户转私户</option>
                    {% else %}
                        <option value="reverse_sg">私户转公户</option>
                    {% endif %}
                </select>
                <button class="btn btn-warning">go</button>
            </div>

            <table class="table table-hover table-striped table-bordered">
                <thead>
                <tr>
                    <th><input type="checkbox" id="select_all"> 选择</th>
                    <th>序号</th>
                    <th>编号</th>
                    <th>姓名</th>
                    <th>性别</th>
                    <th>qq</th>
                    <th>报名状态</th>
                    <th>跟踪记录</th>
                    <th>销售</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for foo in customers_obj %}
                    <tr>
                        <td><input type="checkbox" name="cids" value="{{ foo.pk }}"></td>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ foo.id }}</td>
                        <td>{{ foo.name }}</td>
                        <td>{{ foo.get_sex_display }}</td>
                        <td>{{ foo.qq }}</td>
                        <td>{{ foo.status_show }}</td>
                        <td>
                            <a href="{% url 'consult_record' %}?cid={{ foo.pk }}">查看详情</a>
                        </td>
                        <td>{{ foo.consultant|default:'暂无' }}</td>
                        <td>
{#                            <a href="{% url 'edit_customers' foo.pk %}" class="fa fa-edit"></a>#}
                            <a href="{% resole_url request 'edit_customers' foo.pk %}" class="fa fa-edit">编辑</a>
                        </td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>

            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {{ page_info.pager | safe }}
                </ul>
            </nav>
        </form>


    </div>


{% endblock content %}

CRM/templates/saleshtml/edit_customers.html
{% extends 'starter.html' %}


{% block pageheader %}
    <h1>
        {{ label }}
    </h1>
{% endblock %}


{% block content %}


    <form class="form-horizontal" novalidate method="post" action="">
        {% csrf_token %}
        {% for field in customer_form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-6">
                    {{ field }}
                </div>

                <div class="col-sm-4">
                    {{ field.errors.0 }}
                </div>
            </div>
        {% endfor %}

        <button class="btn btn-success">提交</button>
    </form>



{% endblock %}

CRM/templates/saleshtml/enrollments.html
{% extends 'starter.html' %}

{% block pageheader %}
    <h1>

    报名记录展示
    </h1>
{% load mytags %}
{% endblock %}

{% block content %}
    <a href="{% url 'add_enrollment' %}" class="btn btn-primary">
        添加报名记录
    </a>

    <div class="form-inline">
        <form action="" class="pull-right">
            <div class="form-group pull-right">
                <select name="search_field" id="search_field" class="form-control">
                    <option value="customer__name__contains">客户名称</option>
                </select><input type="text" class="form-control" name="kw" id="key_word" placeholder="请输入关键字"
                                autocomplete="off">
                <button type="submit" class="btn btn-primary">搜索</button>
            </div>
        </form>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group pull-left">
                <select name="action" id="action" class="form-control">

                    <option value="bulk_enroll_record">批量删除</option>


                </select>
                <button class="btn btn-warning">go</button>
            </div>

            <table class="table table-hover table-striped table-bordered">
                <thead>
                <tr>
                    <th><input type="checkbox" id="select_all"> 选择</th>
                    <th>序号</th>
                    <th>为什么报名</th>
                    <th>审批通过</th>
                    <th>报名日期</th>
                    <th>客户名称</th>
                    <th>校区</th>
                    <th>所报班级</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for enroll in enrolls %}
                    <tr>
                        <td><input type="checkbox" name="cids" value="{{ enroll.pk }}"></td>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ enroll.why_us }}</td>
                        <td>{{ enroll.contract_approved }}</td>
                        <td>{{ enroll.enrolled_date|date:'Y-m-d H:i:s' }}</td>
                        <td>{{ enroll.customer }}</td>
                        <td>{{ enroll.school }}</td>
                        <td>{{ enroll.enrolment_class }}</td>
                        <td>
                            <a href="{% resole_url request 'edit_enrollment' enroll.pk %}" class="fa fa-edit">编辑</a>
                            <a href="{% resole_url request 'delete_enroll_record' enroll.pk %}" class="fa fa-remove">删除</a>
                        </td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>

            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {{ page_info.pager | safe }}
                </ul>
            </nav>
        </form>


    </div>

{% endblock content %}

CRM/templates/saleshtml/home.html
{% extends 'starter.html' %}